### ISSUE TITLE
Address display issue

### ISSUE THREAD

**Issue by VeeSheldonYang** [excelsia/vee-wallet-gui#132]
As screen capture below, the address cannot be fully displayed. The full address of recipient is "AR5vkoPtK**************Zcq815vpyq"(missing "q"). It is better to make the window had enough space to show the full address.
![issue2](https://user-images.githubusercontent.com/41148850/46604248-339f2c00-cb28-11e8-929f-fe7a04673eaf.jpeg)

**Comment by Haynar216** [comment]
This issue's fixed--we adjusted the width
